sonar.projectKey=mlops-playground
sonar.projectName=MLOps Playground
sonar.projectVersion=1.0
sonar.sources=backend,app
sonar.exclusions=**/__pycache__/**,**/*.pyc,deployed_models/**,venv/**,.github/**
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
